version: "3.8"

networks:
  network:
    name: network
    driver: bridge

volumes:
  elastic:
    external: true
    name: elastic

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2-arm64
    hostname: elastic
    container_name: elastic
    restart: always
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - network
    volumes:
      - elastic:/var/lib/elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.2-arm64
    hostname: kibana
    container_name: kibana
    restart: always
    depends_on:
      - elastic
    links:
      - elastic
    ports:
      - "5601:5601"
    networks:
      - network
