networks:
  network:
    name: network
    driver: bridge

volumes:
  firebird:
    external: true
    name: firebird

services:
  firebird:
    image: firebirdsql/firebird
    hostname: firebird
    container_name: firebird
    restart: always
    environment:
      - FIREBIRD_ROOT_PASSWORD=masterkey
    ports:
      - 3070:3050
    networks:
      - network
    volumes:
      - /D/:/var/lib/firebird/data
