version: '3.8'

networks:
  network:
    name: network
    driver: bridge

volumes:
  data:
    external: true
    name: firebird

services:
  firebird:
    image: jacobalberty/firebird:v5
    hostname: firebird
    container_name: firebird
    restart: always
    environment:
      ISC_PASSWORD: masterkey
    ports:
      - '3060:3060'
    networks:
      - network
    volumes:
      - data:/var/lib/postgresql/data
