version: "3"
networks:
  network:
    name: network
    driver: bridge
volumes:
  kafka:
    external: true
    name: kafka
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper
    container_name: zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
    networks:
      - network
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka
    container_name: kafka
    restart: always
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - '9092:9092'
    networks:
      - network
    volumes:
      - kafka:/bitnami/kafka
    depends_on:
      - zookeeper
