version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    hostname: keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SCHEMA: public
      DB_DATABASE: keycloak
    ports:
      - "8080:8080"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
