version: '3.9'

networks:
  network:
    name: loki_network
    driver: bridge

volumes:
  loki:
    external: true
    name: loki
  grafana:
    external: true
    name: grafana

services:
  loki:
    image: grafana/loki
    hostname: loki
    container_name: loki
    restart: always
    networks:
      - loki_network
    volumes:
      - loki:/data/loki

  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    depends_on:
      - loki
    restart: always
    links:
      - loki
    ports:
      - 8088:3000
    networks:
      - loki_network
    volumes:
      - grafana:/var/lib/grafana

  nginx:
    image: laurentbel/nginx-basic-auth
    hostname: nginx
    container_name: nginx
    depends_on:
      - loki
    restart: always
    tty: true
    ports:
      - 8080:8080
    environment:
      - FORWARD_HOST=loki
      - FORWARD_PORT=3100
      - BASIC_PASSWORD=admin
      - BASIC_USERNAME=admin
    networks:
      - loki_network
