version: "3.8"
networks:
  network:
    name: network
    driver: bridge
volumes:
  mongo:
    external: true
    name: mongo
services:
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mongodb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - network
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb
