version: "3.8"
networks:
  network:
    name: network
    driver: bridge
volumes:
  data:
    external: true
    name: mysql
services:
  mysql:
    image: mysql/mysql-server:latest
    hostname: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - network
