networks:
  network:
    name: network
    external: true
    driver: bridge

volumes:
  data:
    external: true
    name: mysql

services:
  mysql:
    image: mysql/mysql-server:latest
    hostname: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mysql
    ports:
      - '3306:3306'
    networks:
      - network
    volumes:
      - data:/var/lib/mysql
