version: '3.1'

networks:
  network:
    name: network
    driver: bridge

volumes:
  postgres:
    external: true
    name: postgres

services:
  postgres:
    image: postgres:12.12
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - network
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    depends_on:
      - postgres
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'denernun@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
    ports:
      - '15432:80'
    networks:
      - network
