networks:
  network:
    name: network
    external: true
    driver: bridge

volumes:
  data:
    external: true
    name: postgres

services:
  postgres:
    image: postgres:16.3
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - '5432'
    ports:
      - '5432:5432'
    networks:
      - network
    volumes:
      - data:/var/lib/postgresql/data
