version: "3.1"
services:
  postgres:
    image: postgres:12.5
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres:
    external: true
