version: '3.8'

networks:
  network:
    name: network
    driver: bridge

volumes:
  data:
    external: true
    name: postgres12

services:
  postgres12:
    image: postgres:12.12
    hostname: postgres12
    container_name: postgres12
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - '5433'
    ports:
      - '5433:5433'
    networks:
      - network
    volumes:
      - data:/var/lib/postgresql/data
    command: -p 5433
