version: "3.1"
networks:
  network:
    name: network
    driver: bridge
volumes:
  data:
    name: postgres
services:
  postgres:
    image: postgres:12.5
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - network
    volumes:
      - data:/var/lib/postgresql/data
