version: '3.2'

networks:
  network:
    name: network
    driver: bridge

volumes:
  rabbit:
    external: true
    name: rabbit

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - network
    volumes:
      - rabbit:/var/lib/rabbitmq/
      - rabbit:/var/log/rabbitmq
