networks:
  network:
    name: network
    external: true
    driver: bridge

volumes:
  data:
    external: true
    name: rabbit

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - network
    volumes:
      - data:/var/lib/rabbitmq/
      - data:/var/log/rabbitmq
