networks:
  network:
    name: network
    external: true
    driver: bridge

volumes:
  data:
    external: true
    name: redis

services:
  redis:
    image: redis
    hostname: redis
    container_name: redis
    restart: always
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    ports:
      - '6379:6379'
    networks:
      - network
    volumes:
      - data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  redisinsight:
    image: redis/redisinsight:latest
    hostname: redisinsight
    container_name: redisinsight
    restart: always
    ports:
      - '5540:5540'
    networks:
      - network
    depends_on:
      - redis
