version: "3.8"
services:
  redis:
    image: redis
    hostname: redis
    container_name: redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - network
    command: redis-server

networks:
  network:
    driver: bridge

volumes:
  redis:
    external: true
