version: '3.8'
networks:
  network:
    name: network
    driver: bridge
volumes:
  data:
    external: true
    name: seq
services:
  seq:
    image: datalust/seq
    hostname: seq
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - data:/data
    ports:
      - '5341:80'
    networks:
      - network
