version: "3.8"
services:
  # sonarqube-postgres:
  #   image: postgres
  #   hostname: sonarqube-postgres
  #   container_name: sonarqube-postgres
  #   networks:
  #     - sonarqube
  #   environment:
  #     - POSTGRES_USER=sonar
  #     - POSTGRES_PASSWORD=sonar
  #   volumes:
  #     - postgres:/var/lib/postgresql
  #     - postgres-data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:8.2-community
    hostname: sonarqube
    container_name: sonarqube
    # environment:
    #   - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    #   - SONARQUBE_JDBC_USERNAME=sonar
    #   - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      # docker volume create --name=x
      - sonar-conf:/opt/sonarqube/conf
      - sonar-data:/opt/sonarqube/data
      - sonar-logs:/opt/sonarqube/logs
      - sonar-ext:/opt/sonarqube/extensions
      - sonar-plugins:/opt/sonarqube/lib/bundled-plugins
    expose:
      - 9000
    ports:
      - "9000:9000"
    networks:
      - network

volumes:
  # postgres:
  #   external: true
  # postgres-data:
  #   external: true
  sonar-conf:
    external: true
  sonar-data:
    external: true
  sonar-logs:
    external: true
  sonar-ext:
    external: true
  sonar-plugins:
    external: true

networks:
  network:
    driver: bridge
