networks:
  network:
    name: network
    external: true
    driver: bridge

volumes:
  n8n:
    external: true
    name: n8n

services:
  n8n:
    image: n8nio/n8n:latest
    hostname: n8n
    container_name: n8n
    restart: always
    environment:
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      NODE_ENV: production
      N8N_BASIC_AUTH_ACTIVE: false
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: YourStr0ngP@ssw0rd!
      N8N_ENCRYPTION_KEY: your-very-secure-32char-encryption-key
      DB_TYPE: sqlite
      DB_SQLITE_FILENAME: /data/.n8n/database.sqlite
    ports:
      - '8080:5678'
    networks:
      - network
    volumes:
      - n8n:/data
