apiVersion: 1

datasources:
  # Loki datasource
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
    isDefault: true
    editable: true

  # PostgreSQL datasource
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: postgres
    user: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: postgres
    isDefault: false
    editable: true
