server {
  listen 80;
  server_name grafana.erpclass.com.br;
  return 301 https://$host$request_uri;
}

map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

server {

  listen 443 ssl;
  server_name grafana.erpclass.com.br;

  ssl_certificate /etc/letsencrypt/live/erpclass.com.br/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/erpclass.com.br/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/erpclass.com.br/chain.pem;

  include /etc/nginx/general.conf;

  location / {
    # Usar hostname do container Docker, não localhost
    proxy_pass http://grafana:3000;
    include /etc/nginx/proxy.conf;
  }

}
